/// These names are turned into strings and sent straight to analytics.
/// WARNING: Changing these names will change how analytics are grouped.
///
/// We can add a `toAnalyticsName` helper if they need to diverge
enum AnalyticsPage {
  allFriendRequests,
  allSuggestedFriends,
  avatarProposal,
  accountSettings,
  accountDeletion,
  accountDeletionReason,
  debug,
  error,
  feed,
  friends,
  onboardingFriends,
  friendshipUserList,
  gmaQuestion,
  gmaSplash,
  invite,
  inviteCode,
  landing,
  login,
  me,
  myFriends,
  onboarding,
  overview,
  payoff,
  profile,
  question,
  questionShare,
  waitlist,
  waitlistNotInSchool,
  waitlistSuccess,
  unknown,
  profileShare,
  topMatchesList,
  kmaYourselfPage,
  kmaYourselfSplashPage,
  myLeaderboardPage,
  scoreboard,
  kmaFetcher,
  imageUpload,

  // Ping
  pingHome,
  defaultBottomSheet,
  qrFriendingPage,
  permissionFlowPage,
  onboardingFriendingPage,
  levelUpPage,
  broadcastSelect,
  broadcastSelectGroup,
  broadcastEditGroup,
  pingRewindPage,
  pingSelfProfile,
  stealthModeSheet,

  // SameSame
  sameQuestion,
  sameQuestionLoading,
  sameCooldown,
  sameClaimSticker,
  sameEmptyClaim,
  sameStickerbook,
  sameProfilePage,
  pingProfilePage,
  permissionExplainer,
  friendshipSettings,
  userSettings,
  ambassadorPage,
  levelsExplainer,
  pointsExplainer,
  invitePage,
  broadcastShareSheet,
  contactSupport,
  editProfile,
  broadcastModeSelect,
  hangSpotSheet,
  closeFriendsSelect,
  badgeClaim,
  badgeDetail,
  badgeBook,
  statusSheet,
  locationVisibilitySheet,
  allFriends,
  locationVisibilityExplainer,
  nonFriendProfilePage,
  onboardingFirstName,
  onboardingLastName,
  onboardingBirthday,
  onboardingEmail,
  onboardingPhoneNumber,
  onboardingVerificationCode,
  onboardingSchoolWaitlist,
  onboardingWaitlist,
  onboardingContactsPermission,
  onboardingImageUpload,
  onboardingConnections,
  onboardingWelcome,
  onboardingLocationPermissionWhenInUse,
  onboardingLocationPermissionAlways,
  onboardingLocationPermissionNever,
  onboardingNonStudentEmail,
  onboardingOutboundVerification,
  onboardingCountrySelector,
  onboardingSetStatus,
  statusStreakExplainer,
  customPing,
  ftux,
  statusReplySheet,
  statusReplyNonFriend,
  campusFeed,
  onboardingAppReview,
  giveaway,
}

/// https://stackoverflow.com/a/59308734/1759443
extension ParseToString on AnalyticsPage {
  String toShortString() {
    return toString().split('.').last;
  }
}
